# SD701

## Sparse matrices

The objective of this notebook is to learn to work with sparse matrices.

## Import

In [1]:
import numpy as np

In [2]:
import scipy.sparse as sparse

## Data structure

We first focus on the [csr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)  (Compressed Sparse Row) format. 

In [3]:
# random matrix (dense format)
X_dense = np.random.randint(2, size = (10,5))

In [4]:
X_csr = sparse.csr_matrix(X_dense)

In [5]:
X_csr

<10x5 sparse matrix of type '<class 'numpy.int64'>'
	with 23 stored elements in Compressed Sparse Row format>

In [6]:
X_csr.shape

(10, 5)

In [7]:
X_csr.nnz

23

The data structure consists of 3 vectors:

In [8]:
X_csr.indices

array([0, 4, 2, 4, 0, 2, 3, 4, 0, 3, 4, 1, 1, 2, 1, 2, 3, 1, 4, 0, 1, 2,
       3], dtype=int32)

In [9]:
X_csr.indptr

array([ 0,  2,  4,  8, 11, 12, 13, 14, 17, 19, 23], dtype=int32)

In [10]:
X_csr.data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

Changing these vectors changes the matrix:

In [11]:
X_csr.data = np.random.choice((1,2,3,4,5), size = len(X_csr.data))

In [12]:
np.array(X_csr.todense())

array([[1, 0, 0, 0, 2],
       [0, 0, 4, 0, 3],
       [5, 0, 4, 5, 2],
       [5, 0, 0, 4, 2],
       [0, 5, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 3, 3, 4, 0],
       [0, 2, 0, 0, 5],
       [5, 4, 2, 4, 0]])

In [13]:
X_dense = np.array(X_csr.todense())

The [csc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format is the analogue of the csr format for columns.

In [14]:
X_csc = sparse.csc_matrix(X_dense)

In [15]:
X_csc

<10x5 sparse matrix of type '<class 'numpy.int64'>'
	with 23 stored elements in Compressed Sparse Column format>

In [16]:
# transposing a matrix in csr format is a matrix in csc format
X_csr.T

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 23 stored elements in Compressed Sparse Column format>

## Construction

In practice, sparse data are stored as a list of pairs (row id, col id) triplets (row id, col id, value) in text or csv files.<br> 
This is the [coo](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html) (COOrdinate) format. 

In [17]:
X_coo = sparse.coo_matrix(X_dense)

In [18]:
X_coo.row

array([0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 5, 6, 7, 7, 7, 8, 8, 9, 9, 9,
       9], dtype=int32)

In [19]:
X_coo.col

array([0, 4, 2, 4, 0, 2, 3, 4, 0, 3, 4, 1, 1, 2, 1, 2, 3, 1, 4, 0, 1, 2,
       3], dtype=int32)

In [20]:
X_coo.data

array([1, 2, 4, 3, 5, 4, 5, 2, 5, 4, 2, 5, 2, 5, 3, 3, 4, 2, 5, 5, 4, 2,
       4])

Sparse matrices can be easily moved from one format to another. This can be used to get the list of entries of a matrix in CSR format:

In [21]:
X_coo = sparse.coo_matrix(X_csr)

In [22]:
X_coo.row

array([0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 5, 6, 7, 7, 7, 8, 8, 9, 9, 9,
       9], dtype=int32)

In [23]:
X_coo.col

array([0, 4, 2, 4, 0, 2, 3, 4, 0, 3, 4, 1, 1, 2, 1, 2, 3, 1, 4, 0, 1, 2,
       3], dtype=int32)

In [24]:
X_csr = sparse.csr_matrix(X_coo)

In [25]:
X_csr

<10x5 sparse matrix of type '<class 'numpy.int64'>'
	with 23 stored elements in Compressed Sparse Row format>

Construction of a matrix from a list of links:

In [26]:
n, m = 100, 200

In [27]:
pairs = [(np.random.choice(n), np.random.choice(m)) for i in range(100)]

In [28]:
row = [pair[0] for pair in pairs]
col = [pair[1] for pair in pairs]
data = np.ones_like(row)

In [29]:
X = sparse.csr_matrix((data, (row, col)), shape = (n, m))

In [30]:
X

<100x200 sparse matrix of type '<class 'numpy.int64'>'
	with 99 stored elements in Compressed Sparse Row format>

Zero matrix:

In [31]:
X = sparse.csr_matrix((n,m))

In [32]:
X

<100x200 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

Diagonal matrix:

In [33]:
X = sparse.diags(np.arange(5))

In [34]:
X

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements (1 diagonals) in DIAgonal format>

In [35]:
X = sparse.csr_matrix(X)

In [36]:
X

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [51]:
X = sparse.csr_matrix(np.random.randint(2, size = (10,5)))

In [52]:
X

<10x5 sparse matrix of type '<class 'numpy.int64'>'
	with 28 stored elements in Compressed Sparse Row format>

1. Set one of the entries to 0 by modifying the data vector. 
2. What do you observe on the number of non-zero entries stored?
3. Use the following method to get the matrix in proper format.

In [53]:
print(f"Number of non-zero values before modifying X.data: {X.nnz}")
X.data[1] = 0
print(f"Number of non-zero values after modifying X.data: {X.nnz}")

Number of non-zero values before modifying X.data: 28
Number of non-zero values after modifying X.data: 28


In [54]:
X.eliminate_zeros()

In [55]:
print(X.nnz)

27


When we modify the data vector to set an entry to $0$ (here, `X.data[1]`, we notice that the number of non-zero values does not decrease (as can be seen by printing the value of `X.nnz` before and after the modification). This is because scipy makes a difference between "non-zero values" (i.e. unset values) and set values that happen to be set to 0. We can use the `X.eliminate_zeros()` function to consider all $0$ as unset

## Operations

Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.

In [56]:
n, m = 10, 15

pairs = [(np.random.choice(n), np.random.choice(m)) for i in range(20)]

row = [pair[0] for pair in pairs]
col = [pair[1] for pair in pairs]
data = np.ones_like(row)

In [57]:
X = sparse.csr_matrix((data, (row, col)), shape = (n, m))

In [58]:
X.dot(np.ones(m))

array([1., 3., 1., 2., 2., 1., 1., 2., 3., 4.])

In [59]:
X.T.dot(np.ones(n))

array([0., 0., 1., 1., 2., 0., 2., 2., 2., 3., 2., 1., 3., 0., 1.])

In [60]:
X.T.dot(X)

<15x15 sparse matrix of type '<class 'numpy.int64'>'
	with 33 stored elements in Compressed Sparse Column format>

In [61]:
X.dot(X.T)

<10x10 sparse matrix of type '<class 'numpy.int64'>'
	with 26 stored elements in Compressed Sparse Row format>

In [62]:
X.data = np.random.choice((1,2,3,4), size = len(X.data))

In [63]:
X

<10x15 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [64]:
Y = X > 1

In [65]:
Y

<10x15 sparse matrix of type '<class 'numpy.bool_'>'
	with 14 stored elements in Compressed Sparse Row format>

In [66]:
pairs = [(np.random.choice(n), np.random.choice(m)) for i in range(20)]

row = [pair[0] for pair in pairs]
col = [pair[1] for pair in pairs]
data = np.ones_like(row)

In [67]:
Y = sparse.csr_matrix((data, (row, col)), shape = (n, m))

In [68]:
2 * X + 5 * Y

<10x15 sparse matrix of type '<class 'numpy.int64'>'
	with 34 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [159]:
X = sparse.csr_matrix(np.random.randint(2, size = (20,3)))
# For simple tests:
# X = sparse.csr_matrix([[1,1], [1,0]])

* Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero). 
* Do the same for columns.

In [160]:
n, m = X.shape 

In [161]:
normalizing_diag = sparse.csr_matrix(sparse.diags(X.dot(np.ones(m))))

In [162]:
normalizing_diag.data = 1 / normalizing_diag.data

Once we have the `normalizing_diag` matrix (that contains the number of non zero values per row), we can simply multiply `X` by this matrix to obtain row normalization.
Notice that to normalize by columns, we have to adapt the normalization matrix (see below).
`normalizing_diag` multiplies `X` by a vector of $1$'s. This is matrix multiplication, so in practice the value of the i-th element of the vector is the sum of each row. `sparse.diags` transforms this vector into a diagonal matrix (everything is $0$ except the diagonal, that is required for the dimensions to match.

In [163]:
normalizing_diag_cols = sparse.csr_matrix(sparse.diags(X.T.dot(np.ones(n))))
normalizing_diag_cols.data = 1/normalizing_diag_cols.data

In [164]:
X_row_norm = normalizing_diag * X
X_col_norm = normalizing_diag_cols * X.T

In [165]:
X_row_norm.todense(), X_col_norm.T.todense()

(matrix([[0.5       , 0.5       , 0.        ],
         [1.        , 0.        , 0.        ],
         [0.5       , 0.5       , 0.        ],
         [0.33333333, 0.33333333, 0.33333333],
         [0.5       , 0.        , 0.5       ],
         [0.5       , 0.5       , 0.        ],
         [0.        , 1.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.5       , 0.5       ],
         [0.        , 1.        , 0.        ],
         [0.5       , 0.        , 0.5       ],
         [0.        , 0.        , 1.        ],
         [0.5       , 0.5       , 0.        ],
         [0.33333333, 0.33333333, 0.33333333],
         [0.        , 0.        , 1.        ],
         [0.5       , 0.        , 0.5       ],
         [0.        , 0.5       , 0.5       ],
         [0.5       , 0.        , 0.5       ],
         [0.        , 0.        , 0.        ],
         [0.5       , 0.5       , 0.        ]]),
 matrix([[0.08333333, 0.09090909, 0.        ],
         [0

## Slicing

Sparse matrices can be sliced like numpy arrays. The CSR format is more efficient for row slicing (although column slicing is possible), while the CSC format is more efficient for column slicing.

In [166]:
X = sparse.csr_matrix(np.random.randint(2, size = (10,5)))

In [167]:
X[1]

<1x5 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [168]:
X[1].todense()

matrix([[1, 0, 0, 1, 0]])

In [169]:
X[:3]

<3x5 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [170]:
X[:3].todense()

matrix([[1, 1, 0, 0, 1],
        [1, 0, 0, 1, 0],
        [1, 0, 0, 1, 0]])